uploads = []
outputs = []

[[generated]]
id = "LB5Paxi3H8L_YNsackwlF"
uri = "file://artifacts/pepewife/public/pepewife-hero.png"
type = "image"
title = "pepewife female pepe frog mascot"

[[generated]]
id = "FoxqBgfdhrViayDjmxlg-"
uri = "file://artifacts/pepewife/public/pepewife-bg.png"
type = "image"
title = "female pepe rocket solana network background"

[[generated]]
id = "ZfYkah5EQtGsWlKMZ0sd_"
uri = "file://artifacts/pepewife/public/bg-presale.png"
type = "image"
title = "bg-presale.png section bg"

[[generated]]
id = "uBCQ4cBeB1G8ynxqG_S78"
uri = "file://artifacts/pepewife/public/bg-why.png"
type = "image"
title = "bg-why.png section bg"

[[generated]]
id = "dhpxmP9VhylZDsR1HjdEU"
uri = "file://artifacts/pepewife/public/bg-howtobuy.png"
type = "image"
title = "bg-howtobuy.png section bg"

[[generated]]
id = "ASaVwZoJEW2vtWT7ZOL5L"
uri = "file://artifacts/pepewife/public/bg-tokenomics.png"
type = "image"
title = "bg-tokenomics.png section bg"

[[generated]]
id = "ZlMtxrYETD0KXxrXs58bV"
uri = "file://artifacts/pepewife/public/bg-roadmap.png"
type = "image"
title = "bg-roadmap.png section bg"

[[generated]]
id = "Eus9rYV1-OmRh5CaQ4h5U"
uri = "file://artifacts/pepewife/public/bg-community.png"
type = "image"
title = "bg-community.png section bg"

[[generated]]
id = "kjwBR98ruB1rckE0BItM1"
uri = "file://artifacts/pepewife/public/tokenomics-mascot.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NvftmDr-ixzznBQuwp5x-"
uri = "file://artifacts/pepewife/public/roadmap-phase1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "eB0kbTdgsqqZwk73Ys2j3"
uri = "file://artifacts/pepewife/public/roadmap-phase2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "b0XJS_w1jTRnhvS3W_L84"
uri = "file://artifacts/pepewife/public/roadmap-phase3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cbPvrZGku7r6DivuzGyLP"
uri = "file://artifacts/pepewife/public/roadmap-phase4.png"
type = "image"
title = "generated_image"
