[[pages]]
path = "/"
screenshotTimestamp = "2026-04-04T17:56:51Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afa6591-9a46-45cf-882d-be0352148609/1e4e58d6-f55c-424b-9140-dbd7690d7cce/eOZghhY"

[[pages]]
path = "/admin/dashboard"
screenshotTimestamp = "2026-04-04T17:30:03Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afa6591-9a46-45cf-882d-be0352148609/1e4e58d6-f55c-424b-9140-dbd7690d7cce/zjNCy5D"

[[pages]]
path = "/connect"
screenshotTimestamp = "2026-04-04T17:57:08Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/6afa6591-9a46-45cf-882d-be0352148609/1e4e58d6-f55c-424b-9140-dbd7690d7cce/SRymWsx"
